format = """
[](#303030)\
$os\
$username\
[](bg:#0072b3 fg:#303030)\
$directory\
[](fg:#0072b3 bg:#c4a000)\
$git_branch\
$git_status\
[](fg:#c4a000 bg:#303030)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#303030 bg:#001d3e)\
$docker_context\
[](fg:#001d3e bg:#3b5454)\
$time\
[ ](fg:#3b5454)\
\n$character
"""

# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below

[username]
show_always = true
style_user = "bg:#303030"
style_root = "bg:#303030"
format = '[$user ]($style)'
disabled = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[     os]
style = "bg:#303030"
disabled = false # Disabled by default

[directory]
style = "bg:#0072b3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#303030"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#001d3e"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#303030"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#303030"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#c4a000"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#c4a000"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#303030"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#303030"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#303030"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#303030"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#303030"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#303030"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#303030"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#303030"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#3b5454"
format = '[ $time ]($style)'

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "
